version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: hugo install
          command: |
              go get -v github.com/gohugoio/hugo
              git config --global user.name "iceEiji"
              git config --global user.email "guitar.pg.sc@gmail.com"
      - run:
          name: hugo & update master
          command: |
            hugo
            git add .
            git commit -m "run \"hugo\" command."
            git push origin source
            git subtree push --prefix docs/ origin master
